# Generated by Django 4.2.6 on 2023-11-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado')], default='livre', max_length=10)),
                ('passeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviço.prestacaoservicos')),
            ],
        ),
    ]
