# Generated by Django 4.2.6 on 2023-11-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviço', '0002_horariotrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoservicos',
            name='fim',
            field=models.TimeField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='19:00'),
        ),
        migrations.AddField(
            model_name='prestacaoservicos',
            name='inicio',
            field=models.TimeField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='06:00'),
        ),
        migrations.DeleteModel(
            name='HorarioTrabalho',
        ),
    ]
