# Generated by Django 4.2.6 on 2023-11-17 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0005_selecaohorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecaoDeHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=20)),
                ('status', models.CharField(default='solicitado', max_length=20)),
                ('passeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes_passeador', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecoes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SelecaoHorario',
        ),
    ]
