# Generated by Django 4.2.6 on 2023-11-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0006_selecaodehorario_delete_selecaohorario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecaoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_passeador', models.IntegerField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
