# Generated by Django 4.2.6 on 2023-11-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0008_solicitacaopasseio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecionarHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=20)),
                ('status', models.CharField(default='solicitado', max_length=20)),
                ('id_passeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviço.prestacaoservicos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitacaopasseio',
            name='passeador',
        ),
        migrations.RemoveField(
            model_name='solicitacaopasseio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='SelecaoHorario',
        ),
        migrations.DeleteModel(
            name='SolicitacaoPasseio',
        ),
    ]
