# Generated by Django 4.2.6 on 2023-11-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_tipousuario_image'),
        ('Serviço', '0009_selecionarhorario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecionarhorario',
            name='id_passeador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.tipousuario'),
        ),
    ]
