# Generated by Django 4.2.6 on 2023-11-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serviço', '0010_alter_selecionarhorario_id_passeador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecionarhorario',
            name='id_passeador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviço.prestacaoservicos'),
        ),
    ]
