# Generated by Django 4.2.6 on 2023-11-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0011_alter_selecionarhorario_id_passeador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecionarHorario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_passeador', models.IntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('status', models.CharField(default='solicitado', max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
