# Generated by Django 4.2.6 on 2023-11-20 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Serviço', '0012_selecionarhorario2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaoservicos',
            name='passeador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='selecionarhorario',
            name='id_passeador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviço.prestacaoservicos', to_field='passeador_id'),
        ),
        migrations.DeleteModel(
            name='SelecionarHorario2',
        ),
    ]
