# Generated by Django 4.2.6 on 2023-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviço', '0017_alter_selecionarhorario_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecionarhorario',
            name='numero',
            field=models.CharField(default='Numero', max_length=20),
        ),
    ]
