# Generated by Django 4.2.6 on 2023-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviço', '0022_selecionarhorario_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopasseio',
            name='id_passeio',
        ),
        migrations.RemoveField(
            model_name='selecionarhorario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='selecionarhorario',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='selecionarhorario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='selecionarhorario',
            name='rua',
        ),
        migrations.AddField(
            model_name='infopasseio',
            name='status',
            field=models.CharField(default='Solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopasseio',
            name='numero',
            field=models.CharField(default='Numero', max_length=20),
        ),
        migrations.AlterField(
            model_name='infopasseio',
            name='rua',
            field=models.CharField(default='Rua', max_length=100),
        ),
    ]
