# Generated by Django 4.2.6 on 2023-11-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Serviço', '0023_remove_infopasseio_id_passeio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopasseio',
            name='status',
        ),
        migrations.AddField(
            model_name='infopasseio',
            name='id_passeio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Serviço.selecionarhorario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infopasseio',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infopasseio',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
